//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUsers
    {
        public long AdminID { get; set; }
        public string AdminUsername { get; set; }
        public string AdminPassword { get; set; }
    
        public virtual BankTable BankTable { get; set; }
    }
}
