//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTable
    {
        public long AccountNumber { get; set; }
        public string FIO { get; set; }
        public string Password { get; set; }
        public string LeavingFrom { get; set; }
        public string GoingTo { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<long> TravelerAmount { get; set; }
        public string FlightType { get; set; }
        public Nullable<double> FlightCost { get; set; }
    }
}
